#!/bin/sh

. /etc/init.d

[ -f /usr/local/sbin/task3.sh ] || exit 0

case "$1" in

        start)
                echo "script started...."
                /usr/local/sbin/task3.sh &
                echo "--------------------"
                touch /var/lock/subsys/task3
                ;;
        stop)
                echo -n "stopping"
                killall -q -9 task3.sh &
                rm -f /var/lock/subsys/task3
                ;;
        status)
                status task3
                ;;
        restart|reload)
                $0 stop
                $0 start
                ;;
        *)
                echo "start, stop, restart|reload, status"
                exit 1
esac

exit 0


